(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const K='concorsoQuestRT.v2',DAY=864e5;
let Q=[],modules=[],session=null,timer=null,deferred=null;
const fresh=()=>({xp:0,streak:0,last:null,answered:0,correct:0,sessions:0,week:'',daily:{},question:{},topic:{},bestExam:0,memoryWins:0,badges:[]});
let S=(()=>{try{return Object.assign(fresh(),JSON.parse(localStorage.getItem(K))||{})}catch{return fresh()}})();
const date=()=>new Date().toLocaleDateString('en-CA');
const week=()=>{const d=new Date(),one=new Date(d.getFullYear(),0,1);return `${d.getFullYear()}-${Math.ceil(((d-one)/DAY+one.getDay()+1)/7)}`};
const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function save(){localStorage.setItem(K,JSON.stringify(S));dashboard()}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),2200)}
function touch(){const t=date(),w=week();if(S.week!==w){S.week=w;S.sessions=0}if(S.last===t)return;if(!S.last)S.streak=1;else S.streak=((new Date(t)-new Date(S.last))/DAY===1)?S.streak+1:1;S.last=t}
function xp(n,msg){S.xp+=n;if(msg)toast(`+${n} XP · ${msg}`)}
function mastery(topic){const a=Q.filter(q=>q.topic===topic);if(!a.length)return 0;return Math.round(a.reduce((sum,q)=>{const z=S.question[q.id];return sum+(z?Math.min(1,(z.correct/Math.max(1,z.seen))*.7+z.box*.1):0)},0)/a.length*100)}
function due(){return Q.filter(q=>S.question[q.id]&&S.question[q.id].next<=date())}
function record(q,ok){touch();const z=S.question[q.id]||{seen:0,correct:0,box:0,next:date()};z.seen++;z.correct+=ok?1:0;z.box=ok?Math.min(5,z.box+1):0;z.next=new Date(Date.now()+(ok?[0,1,3,7,14,30][z.box]:1)*DAY).toLocaleDateString('en-CA');S.question[q.id]=z;const t=S.topic[q.topic]||{answered:0,correct:0};t.answered++;t.correct+=ok?1:0;S.topic[q.topic]=t;S.answered++;S.correct+=ok?1:0;xp(ok?12:2)}
function pick(n,filter=()=>true){const p=Q.filter(filter).map(q=>({q,w:!S.question[q.id]?7:1+(5-S.question[q.id].box)+(1-S.question[q.id].correct/Math.max(1,S.question[q.id].seen))*4})),out=[];while(p.length&&out.length<n){let r=Math.random()*p.reduce((x,y)=>x+y.w,0),i=0;for(;i<p.length;i++){r-=p[i].w;if(r<=0)break}out.push(p.splice(Math.min(i,p.length-1),1)[0].q)}return out}
function dashboard(){if(!Q.length)return;$('#levelValue').textContent=Math.floor(S.xp/250)+1;$('#streakValue').textContent=S.streak;$('#xpValue').textContent=S.xp;$('#accuracyValue').textContent=S.answered?Math.round(S.correct/S.answered*100)+'%':'–';$('#dueValue').textContent=due().length;const done=S.daily[date()]||0;$('#dailyProgress').style.width=Math.min(100,done*10)+'%';$('#dailyBadge').textContent=done>=10?'Completata ✓':`${done}/10`;$('#dailyText').textContent=done>=10?'Missione completata. Puoi comunque allenarti ancora.':'Una sessione mista che privilegia domande nuove e argomenti deboli.';const pct=Math.min(100,S.sessions/5*100);$('#weekPercent').textContent=Math.round(pct)+'%';$('#weekProgress').style.width=pct+'%';renderJourney();renderStats();renderBadges()}
function view(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.viewTarget===name));if(name==='study')renderStudy($('#studySearch')?.value||'');window.scrollTo({top:0,behavior:'smooth'})}
function renderJourney(){const box=$('#journeyMap');if(!box)return;const topics=[...new Set(Q.map(q=>q.topic))];box.innerHTML=topics.map((t,i)=>{const m=mastery(t),open=i===0||mastery(topics[i-1])>=70;return `<button class="journey-node ${open?'':'locked'}" data-topic="${esc(t)}" ${open?'':'disabled'}><span class="node-step">${i+1}</span><div><strong>${esc(t)}</strong><small>${m}% padronanza · ${Q.filter(q=>q.topic===t).length} quesiti</small><div class="progress-track"><span style="width:${m}%"></span></div></div><span>${open?'▶':'🔒'}</span></button>`}).join('');box.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>start('topic',b.dataset.topic))}
function renderStudy(query=''){const box=$('#studyModules');if(!box)return;const x=query.trim().toLowerCase();box.innerHTML=modules.filter(m=>!x||JSON.stringify(m).toLowerCase().includes(x)).map(m=>`<article class="study-card"><span class="badge">${esc(m.stage)}</span><h3>${esc(m.title)}</h3><p>${esc(m.summary)}</p><ul>${m.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul><small>Rif. banca: ${esc(m.sourceRef||'RT2026')}</small></article>`).join('')||'<p>Nessuna scheda trovata.</p>'}
function renderStats(){const box=$('#topicStats');if(!box)return;box.innerHTML=[...new Set(Q.map(q=>q.topic))].map(t=>{const z=S.topic[t]||{answered:0,correct:0},p=z.answered?Math.round(z.correct/z.answered*100):0;return `<div class="topic-row"><span>${esc(t)}</span><strong>${z.answered?`${p}% (${z.correct}/${z.answered})`:'Non iniziato'}</strong></div>`}).join('')}
function renderBadges(){const all=[['🔥','Costanza',S.streak>=3],['🧠','Ripasso',due().length===0&&S.answered>=10],['🎯','Precisione',S.answered>=20&&S.correct/S.answered>=.8],['⚡','Allenato',S.answered>=50],['🏆','Esame',S.bestExam>=21]];$('#badgeGrid').innerHTML=all.map(([i,n,u])=>`<div class="achievement ${u?'earned':''}"><span>${i}</span><strong>${n}</strong><small>${u?'Sbloccato':'Da sbloccare'}</small></div>`).join('')}
function start(mode,arg){let items=[],title='Allenamento',exam=false,seconds=0;if(mode==='daily'){items=pick(10);title='Sfida quotidiana'}else if(mode==='review'){items=shuffle(due()).slice(0,15);if(!items.length)items=pick(10);title='Ripasso smart'}else if(mode==='topic'){items=pick(12,q=>q.topic===arg);title=arg}else if(mode==='exam'){items=shuffle(Q.filter(q=>q.stage==='scritta')).slice(0,30);title='Simulazione prova scritta';exam=true;seconds=30*60}else if(mode==='sprint'){items=pick(Math.min(40,Q.length));title='Sprint 60 secondi';seconds=60}else return;if(!items.length)return toast('Nessun quesito disponibile');session={mode,title,items,index:0,score:0,exam,answers:[],seconds};$('#sessionOverlay').classList.remove('hidden');$('#sessionMode').textContent=exam?'Modalità esame':'Allenamento';$('#sessionTitle').textContent=title;if(seconds)startTimer(seconds);else $('#sessionTimer').classList.add('hidden');showQuestion()}
function showQuestion(){const q=session.items[session.index],n=session.items.length;$('#sessionProgress').style.width=(session.index/n*100)+'%';$('#sessionBody').innerHTML=`<div class="question-meta"><span class="badge">${esc(q.stage)}</span><span class="badge">${esc(q.topic)}</span><span class="badge">Difficoltà ${q.difficulty||1}</span></div><h3>${esc(q.prompt)}</h3><div class="answer-list">${q.options.map((a,i)=>`<button class="answer-btn" data-answer="${i}"><strong>${String.fromCharCode(65+i)}</strong>${esc(a)}</button>`).join('')}</div>`;$('#sessionFooter').innerHTML=`<span>${session.index+1}/${n}</span><span>${session.score} corrette</span>`;$$('[data-answer]').forEach(b=>b.onclick=()=>answer(+b.dataset.answer))}
function answer(i){const q=session.items[session.index],ok=i===q.answer;session.answers.push({q,i,ok});if(ok)session.score++;record(q,ok);if(session.mode==='daily')S.daily[date()]=Math.min(10,(S.daily[date()]||0)+1);save();if(session.exam){nextQuestion();return}$$('[data-answer]').forEach((b,j)=>{b.disabled=true;if(j===q.answer)b.classList.add('correct');else if(j===i)b.classList.add('wrong')});$('#sessionBody').insertAdjacentHTML('beforeend',`<div class="explanation ${ok?'ok':'ko'}"><strong>${ok?'✓ Corretta':'✗ Da ripassare'}</strong><p>${esc(q.explanation)}</p><small>Fonte: ${esc(sourceLabel(q.source))}</small></div>`);$('#sessionFooter').innerHTML=`<span>${session.index+1}/${session.items.length}</span><button id="nextQuestion" class="primary-btn">${session.index+1===session.items.length?'Risultato':'Prossima'}</button>`;$('#nextQuestion').onclick=nextQuestion}
function nextQuestion(){session.index++;if(session.index>=session.items.length)return finish();showQuestion()}
function finish(){clearInterval(timer);timer=null;const n=session.items.length,p=Math.round(session.score/n*100),exam=session.exam;touch();S.sessions++;xp(Math.round(session.score*3),exam?'simulazione completata':'sessione completata');if(exam){const trentesimi=Math.round(session.score/n*30*10)/10;S.bestExam=Math.max(S.bestExam,trentesimi);$('#sessionBody').innerHTML=`<div class="result-card"><span class="result-emoji">${trentesimi>=21?'🏆':'📚'}</span><h3>${trentesimi}/30</h3><p>${session.score} risposte corrette su ${n}. ${trentesimi>=21?'Soglia 21/30 raggiunta.':'Sotto la soglia 21/30: usa il ripasso smart.'}</p></div>`}else $('#sessionBody').innerHTML=`<div class="result-card"><span class="result-emoji">${p>=80?'🌟':'💪'}</span><h3>${p}%</h3><p>${session.score} corrette su ${n}. Gli errori rientreranno nel ripasso adattivo.</p></div>`;$('#sessionProgress').style.width='100%';$('#sessionFooter').innerHTML='<button id="finishSession" class="primary-btn wide">Torna alla Home</button>';$('#finishSession').onclick=closeSession;save()}
function startTimer(sec){session.seconds=sec;$('#sessionTimer').classList.remove('hidden');const tick=()=>{const m=Math.floor(session.seconds/60),s=session.seconds%60;$('#sessionTimer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;if(session.seconds--<=0){clearInterval(timer);finish()}};tick();timer=setInterval(tick,1000)}
function closeSession(){clearInterval(timer);timer=null;session=null;$('#sessionOverlay').classList.add('hidden');$('#sessionTimer').classList.add('hidden');view('home');dashboard()}
const memoryPairs=[['DNS','Risoluzione nomi'],['HTTPS','Porta 443'],['SMTP','Invio posta'],['NTP','Sincronizzazione oraria'],['VPN','Tunnel protetto'],['MFA','Più fattori'],['WAF','Protezione web'],['RPO','Perdita dati tollerabile'],['RTO','Tempo di ripristino'],['ACID','Proprietà transazioni'],['grep','Ricerca testo'],['chmod','Modifica permessi']];
const bugs=[['SQL','SELECT reparto, COUNT(*)\nFROM utenti;','La query deve contare gli utenti per reparto. Che cosa manca?',['GROUP BY reparto','ORDER BY COUNT','DROP TABLE utenti','COMMIT reparto'],0,'Una colonna non aggregata presente nella SELECT deve essere raggruppata.'],['Linux','chmod 777 /etc/app/config.ini','Qual è il rischio più evidente?',['Permessi eccessivi a tutti','Il file diventa cifrato','Il file viene cancellato','La rete si disabilita'],0,'777 viola normalmente il principio del minimo privilegio.'],['Reti','IP: 192.168.10.25/24\nGateway: 192.168.20.1','Perché il client può non raggiungere reti esterne?',['Gateway fuori subnet','IP sempre pubblico','/24 è IPv6','Manca SMTP'],0,'Il gateway deve essere direttamente raggiungibile nella subnet locale.']];
function memory(){const sel=shuffle(memoryPairs).slice(0,6),cards=shuffle(sel.flatMap((p,i)=>p.map(text=>({i,text}))));let first=null,locked=false,found=0;const stage=$('#gameStage');stage.classList.remove('hidden');stage.innerHTML=`<h3>Memory tecnico</h3><p>Abbina termine e significato.</p><div class="memory-grid">${cards.map((c,k)=>`<button class="memory-card" data-k="${k}" data-pair="${c.i}"><span>?</span><b>${esc(c.text)}</b></button>`).join('')}</div>`;stage.querySelectorAll('.memory-card').forEach(c=>c.onclick=()=>{if(locked||c.classList.contains('matched')||c===first)return;c.classList.add('open');if(!first){first=c;return}if(c.dataset.pair===first.dataset.pair){c.classList.add('matched');first.classList.add('matched');first=null;found++;xp(5);if(found===sel.length){S.memoryWins++;xp(20,'memory completato');save();toast('Memory completato!')}}else{locked=true;setTimeout(()=>{c.classList.remove('open');first.classList.remove('open');first=null;locked=false},700)}})}
function errorHunt(){const b=bugs[Math.floor(Math.random()*bugs.length)],stage=$('#gameStage');stage.classList.remove('hidden');stage.innerHTML=`<h3>🐞 Caccia all'errore · ${b[0]}</h3><pre>${esc(b[1])}</pre><p>${esc(b[2])}</p><div class="answer-list">${b[3].map((x,i)=>`<button class="answer-btn" data-bug="${i}">${esc(x)}</button>`).join('')}</div><div id="bugFeedback"></div>`;stage.querySelectorAll('[data-bug]').forEach(x=>x.onclick=()=>{const ok=+x.dataset.bug===b[4];$('#bugFeedback').innerHTML=`<div class="explanation ${ok?'ok':'ko'}"><strong>${ok?'✓ Esatto':'✗ Non proprio'}</strong><p>${esc(b[5])}</p></div>`;if(ok){xp(15,'bug trovato');save()}stage.querySelectorAll('[data-bug]').forEach(y=>y.disabled=true)})}
function oral(){const prompts=[['Troubleshooting','Un applicativo restituisce HTTP 503 mentre il server risponde al ping. Descrivi diagnosi e ripristino.'],['Sicurezza','Un utente segnala un allegato sospetto già aperto. Descrivi contenimento, analisi e comunicazioni.'],['Backup','Definisci una strategia di backup per un servizio critico con RPO di 4 ore e RTO di 8 ore.'],['Dominio','Un utente non riesce ad autenticarsi al dominio. Imposta una diagnosi ordinata.']],p=prompts[Math.floor(Math.random()*prompts.length)],stage=$('#gameStage');stage.classList.remove('hidden');let sec=120;stage.innerHTML=`<h3>🎙️ Arena orale · ${p[0]}</h3><p class="oral-prompt">${p[1]}</p><div class="oral-timer" id="oralTimer">02:00</div><details><summary>Mostra scaletta dopo aver risposto</summary><ol><li>Definisci il problema e l'impatto.</li><li>Raccogli evidenze e verifica prerequisiti.</li><li>Formula e testa ipotesi in ordine di rischio.</li><li>Descrivi contenimento e soluzione.</li><li>Verifica il ripristino e documenta la prevenzione.</li></ol></details>`;const t=setInterval(()=>{sec--;const e=$('#oralTimer');if(!e)return clearInterval(t);e.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;if(sec<=0){clearInterval(t);toast('Tempo! Valuta chiarezza e completezza.')}},1000)}
function exportData(){const blob=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`concorso-quest-progressi-${date()}.json`;a.click();URL.revokeObjectURL(a.href)}
function importData(f){const r=new FileReader();r.onload=()=>{try{S=Object.assign(fresh(),JSON.parse(r.result));save();toast('Progressi importati')}catch{toast('File non valido')}};r.readAsText(f)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function sourceLabel(s){if(!s)return 'quesito didattico';if(s.kind==='bando-direct')return 'Bando Regione Toscana 2026';if(s.kind==='rt-history-adapted')return `materiale Regione Toscana ${s.year}, quesito adattato`;return 'quesito didattico costruito sul bando 2026'}
async function load(){try{const paths=['data/questions-preselettiva.json','data/questions-scritta.json','data/questions-orale.json','data/study-modules.json'];const [a,b,c,d]=await Promise.all(paths.map(p=>fetch(p,{cache:'no-cache'}).then(r=>{if(!r.ok)throw new Error(p);return r.json()})));Q=[...a,...b,...c];modules=d;bind();dashboard();renderStudy();console.info(`Concorso Quest RT: ${Q.length} quesiti caricati`)}catch(e){console.error(e);$('#main').insertAdjacentHTML('afterbegin','<div class="panel"><strong>Errore caricamento banca dati.</strong><p>Ricarica la pagina o verifica i file nella cartella data/.</p></div>')}}
function bind(){$$('[data-view-target]').forEach(b=>b.onclick=()=>view(b.dataset.viewTarget));$$('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(['daily','review','exam','sprint'].includes(a))start(a);else if(a==='memory')memory();else if(a==='error-hunt')errorHunt();else if(a==='oral')oral()});$('#closeSession').onclick=closeSession;$('#studySearch').oninput=e=>renderStudy(e.target.value);$('#exportBtn').onclick=exportData;$('#importInput').onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$('#resetBtn').onclick=()=>{if(confirm('Azzerare tutti i progressi locali?')){S=fresh();save();toast('Progressi azzerati')}};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(!deferred)return;deferred.prompt();await deferred.userChoice;deferred=null;$('#installBtn').classList.add('hidden')};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn)}
load();
})();